# safety.py — Drop-in safety layer for all Aether model endpoints

import re
from enum import Enum
from dataclasses import dataclass
from typing import Optional

# ── ENUMS ────────────────────────────────────────────────────────────────────

class SafetyLevel(Enum):
    SAFE  = "safe"
    WARN  = "warn"
    BLOCK = "block"

class QueryMode(Enum):
    DISASTER = "disaster"   # gemma4-disaster
    MOONSHOT = "moonshot"   # gemma4-e4b-moonshot
    OCR      = "ocr"        # glm-ocr (image → text)
    STT      = "stt"        # dimavz/whisper-tiny (audio → text)
    DOCUMENT = "document"   # danchev/granite-docling
    TTS      = "tts"        # kokoro-tts (text → speech)
    EMBED    = "embed"      # nomic-embed-text-v2-moe

# ── MODEL REGISTRY ────────────────────────────────────────────────────────────

MODEL_REGISTRY = {
    QueryMode.DISASTER: {
        "ollama_name": "gemma4-disaster:latest",
        "description": "Fine-tuned Gemma 4 E2B — disaster response, survival, triage",
        "base": "Gemma 4 E2B (Unsloth SFT, Q4_K_M)",
        "size_gb": 3.4,
    },
    QueryMode.MOONSHOT: {
        "ollama_name": "gemma4-e4b-moonshot:latest",
        "description": "Fine-tuned Gemma 4 E4B — humanitarian infrastructure, water/energy/food STEM",
        "base": "Gemma 4 E4B (Unsloth SFT, Q4_K_M)",
        "size_gb": 5.3,
    },
    QueryMode.OCR: {
        "ollama_name": "glm-ocr:q8_0",
        "description": "GLM-OCR — document and image text extraction",
        "base": "GLM-OCR Q8",
        "size_gb": 1.6,
    },
    QueryMode.STT: {
        "ollama_name": "dimavz/whisper-tiny:latest",
        "description": "Whisper Tiny — speech to text, multilingual",
        "base": "Whisper Tiny",
        "size_gb": 0.044,
    },
    QueryMode.DOCUMENT: {
        "ollama_name": "danchev/granite-docling:258m",
        "description": "Granite Docling — PDF and document parsing",
        "base": "Granite 258M",
        "size_gb": 0.521,
    },
    QueryMode.TTS: {
        "ollama_name": "kokoro-tts",
        "description": "Kokoro TTS — fast local text-to-speech, 82M params",
        "base": "Kokoro 82M",
        "size_gb": 0.165,
    },
    QueryMode.EMBED: {
        "ollama_name": "nomic-embed-text-v2-moe:latest",
        "description": "Nomic Embed v2 MoE — multilingual text embeddings",
        "base": "Nomic Embed Text v2 MoE",
        "size_gb": 0.957,
    },
}

# ── SAFETY RULES ─────────────────────────────────────────────────────────────

HARD_BLOCK_PATTERNS = [
    # Medication dosing (both orderings)
    r"\b(\d+\s*mg|\d+\s*ml)\b.*\b(give|administer|inject|dose|prescribe)\b",
    r"\b(give|administer|inject|dose|prescribe)\b.*\b(\d+\s*mg|\d+\s*ml)\b",
    r"\b(prescri(be|ption)|rx\b)",
    r"\bdiagnos(e|is|ing)\b",
    r"\bmedication dosage\b",
    r"\bhow much.*\b(morphine|ketamine|epinephrine|adrenaline|insulin|antibiotics)\b",
    # Self harm
    r"\b(suicide|self.harm|kill myself|end my life)\b",
    # Weapons
    r"\b(explosive|bomb|weapon|poison gas)\b",
    # Legal/financial advice
    r"\b(legal advice|sue|lawsuit|invest my money)\b",
]

MEDICAL_WARN_PATTERNS = [
    r"\b(diagnos|symptom|treatment|therapy|surgery|wound|fracture|bleed)\b",
    r"\b(antibiotic|paracetamol|ibuprofen|aspirin|penicillin)\b",
    r"\b(heart attack|stroke|seizure|unconscious|coma)\b",
    r"\b(retinal|diabetic|glaucoma|cataract|blindness|vision loss)\b",
    r"\b(malaria|cholera|typhoid|tuberculosis|dengue)\b",
    r"\b(blood pressure|pulse|oxygen|SPO2)\b",
]

ENGINEERING_WARN_PATTERNS = [
    r"\b(nuclear|reactor|radiation|radioactive)\b",
    r"\b(high voltage|electrical panel|transformer)\b",
    r"\b(structural|load bearing|foundation|seismic)\b",
    r"\b(explosive|flammable|pressurized vessel|boiler)\b",
    r"\b(hydrogen|methane|biogas)\b.*\b(store|storage|tank)\b",
]

# ── DISCLAIMERS ───────────────────────────────────────────────────────────────

DISCLAIMERS = {
    "medical": (
        "⚕️ **Medical Disclaimer:** This is educational information only. "
        "Aether is not a doctor. In emergencies, always consult a trained "
        "health worker, paramedic, or physician. Do not use this information "
        "as a substitute for professional medical advice.\n\n"
    ),
    "engineering": (
        "⚠️ **Engineering Safety Notice:** This guidance is for educational "
        "purposes. Critical infrastructure (electrical, structural, nuclear, "
        "pressurized systems) must be reviewed by a qualified engineer before "
        "implementation. Improper construction can be fatal.\n\n"
    ),
    "general": (
        "ℹ️ **Aether Notice:** Responses are generated by a fine-tuned AI model "
        "and may contain errors. Always verify critical decisions with qualified "
        "local experts and humanitarian organizations (WHO, UNHCR, MSF).\n\n"
    ),
}

BLOCK_RESPONSE = (
    "🚫 **Aether cannot help with this request.**\n\n"
    "This query requires professional expertise that AI cannot safely provide. "
    "Please contact:\n"
    "- **Medical:** Local health worker, MSF, WHO emergency line\n"
    "- **Legal:** Qualified legal professional\n"
    "- **Crisis:** Local emergency services\n\n"
    "Aether is designed for humanitarian infrastructure guidance, not clinical or legal decisions."
)

# ── CORE SAFETY CLASS ─────────────────────────────────────────────────────────

@dataclass
class SafetyResult:
    level: SafetyLevel
    disclaimers: list[str]
    block_reason: Optional[str] = None

class AetherSafety:
    def __init__(self, strict_mode: bool = False):
        self.strict_mode = strict_mode

    def check_query(self, query: str) -> SafetyResult:
        query_lower = query.lower()
        disclaimers = []

        for pattern in HARD_BLOCK_PATTERNS:
            if re.search(pattern, query_lower, re.IGNORECASE):
                return SafetyResult(
                    level=SafetyLevel.BLOCK,
                    disclaimers=[],
                    block_reason=f"Matched blocked pattern: {pattern}"
                )

        for pattern in MEDICAL_WARN_PATTERNS:
            if re.search(pattern, query_lower, re.IGNORECASE):
                if self.strict_mode:
                    return SafetyResult(
                        level=SafetyLevel.BLOCK,
                        disclaimers=[],
                        block_reason="Strict mode: medical pattern detected"
                    )
                disclaimers.append("medical")
                break

        for pattern in ENGINEERING_WARN_PATTERNS:
            if re.search(pattern, query_lower, re.IGNORECASE):
                disclaimers.append("engineering")
                break

        if disclaimers:
            return SafetyResult(level=SafetyLevel.WARN, disclaimers=disclaimers)
        return SafetyResult(level=SafetyLevel.SAFE, disclaimers=[])

    def wrap_response(self, response: str, safety_result: SafetyResult) -> str:
        if safety_result.level == SafetyLevel.BLOCK:
            return BLOCK_RESPONSE
        prefix = ""
        for key in safety_result.disclaimers:
            prefix += DISCLAIMERS.get(key, "")
        if "medical" in safety_result.disclaimers:
            response += f"\n\n---\n{DISCLAIMERS['general'].strip()}"
        return prefix + response

    def get_model_info(self, mode: QueryMode) -> dict:
        info = MODEL_REGISTRY.get(mode, {})
        return {
            "mode": mode.value,
            "model": info.get("ollama_name", "unknown"),
            "description": info.get("description", ""),
            "base": info.get("base", ""),
            "size_gb": info.get("size_gb", 0),
            "disclaimer": "All outputs are educational. Not a substitute for professional advice.",
        }

# ── QUERY ROUTER ─────────────────────────────────────────────────────────────

class AetherRouter:
    MOONSHOT_KEYWORDS = [
        "water", "purif", "solar", "panel", "biogas", "digester",
        "electricity", "generator", "turbine", "hydro", "filter",
        "chlorin", "SODIS", "latrine", "sanitation", "food preserv",
        "ferment", "seed bank", "camp", "refugee", "infrastructure",
        "reactor", "nuclear", "stirling", "thermoelectric", "carnot",
        "micro-hydro", "wind", "betz", "molten salt", "electrolysis",
    ]

    DISASTER_KEYWORDS = [
        "earthquake", "typhoon", "flood", "tsunami", "hurricane",
        "shelter", "evacuation", "rescue", "search", "survivor",
        "triage", "first aid", "emergency", "disaster", "collapse",
        "trapped", "missing", "rubble", "aftershock",
    ]

    def route(self, query: str, has_image: bool = False) -> QueryMode:
        if has_image:
            return QueryMode.OCR

        query_lower = query.lower()
        moonshot_score = sum(1 for kw in self.MOONSHOT_KEYWORDS if kw in query_lower)
        disaster_score = sum(1 for kw in self.DISASTER_KEYWORDS if kw in query_lower)

        if moonshot_score >= disaster_score:
            return QueryMode.MOONSHOT
        return QueryMode.DISASTER
